package kr.co.mdrp.testdao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import kr.co.mdrp.testdao.dao.Person;
import kr.co.mdrp.testdao.dao.Lease;

import kr.co.mdrp.testdao.dao.PersonDao;
import kr.co.mdrp.testdao.dao.LeaseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personDaoConfig;
    private final DaoConfig leaseDaoConfig;

    private final PersonDao personDao;
    private final LeaseDao leaseDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        leaseDaoConfig = daoConfigMap.get(LeaseDao.class).clone();
        leaseDaoConfig.initIdentityScope(type);

        personDao = new PersonDao(personDaoConfig, this);
        leaseDao = new LeaseDao(leaseDaoConfig, this);

        registerDao(Person.class, personDao);
        registerDao(Lease.class, leaseDao);
    }
    
    public void clear() {
        personDaoConfig.clearIdentityScope();
        leaseDaoConfig.clearIdentityScope();
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

    public LeaseDao getLeaseDao() {
        return leaseDao;
    }

}
